title: Daniel
description: Personal blog (with vc)

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main"
